#ifndef _STDAFX
#define _STDAFX
#include <set>
#include <QCoreApplication>
#include <QList>
#include <QSet>
#include <QMap>
#include <QString>
#include <QFile>
#include <QDir>
#include <QDateTime>
#include <QPair>
#include <QTextStream>
#include <QTextCodec>
#include <QRegularExpression>
#include <QLocale>
#include <QFuture>
#include <QFutureWatcher>
#include <QFutureSynchronizer>
#include <QMutex>
#include <QThreadPool>
#include <QtConcurrent/QtConcurrentMap>
#include <QtConcurrent/QtConcurrentRun>
#include <QtAlgorithms>

#include "lc.h"
#include "Spot.h"
#include "Cty.h"
#include "Px.h"
#include "Bands.h"
#include "States.h"
#include "PerBandInfo.h"

#include "Qso.h"
#include "ArrlDxQso.h"
#include "ArrlRttyQso.h"
#include "CqwwQso.h"
#include "CqwwRttyQso.h"
#include "IaruQso.h"
#include "OcDxQso.h"
#include "VhfQso.h"
#include "WpxQso.h"
#include "WpxRyQso.h"

#include "Log.h"
#include "ArrlLog.h"
#include "ArrlDxLog.h"
#include "ArrlRttyLog.h"
#include "CqwwLog.h"
#include "CqwwRttyLog.h"
#include "OcDxLog.h"
#include "VhfLog.h"
#include "WpxLog.h"
#include "WpxRyLog.h"
#include "IaruLog.h"
#include "WrtcLog.h"

#include "Contest.h"
#include "ArrlContest.h"
#include "ArrlDxContest.h"
#include "ArrlRttyContest.h"
#include "IaruContest.h"
#include "VhfContest.h"
#include "CqContest.h"
#include "CqwwContest.h"
#include "CqwwRttyContest.h"
#include "WpxContest.h"
#include "WpxRyContest.h"
#include "OcDxContest.h"
#include "Globals.h"
#endif // _STDAFX